### ISSUE TITLE
Demo app references

### ISSUE THREAD

**Issue by emilbonnek** [xtreamsrl/firebase-ngrx-user-management#11]
The demo app contains references to `@xtream/firebase-ngrx-user-management` in several components and the app module.
It makes forking and local development harder.  I suggest making references to the local lib instead, as is already done in several places. I am making a pull request for this.

**Comment by emilbonnek** [comment]
PR #12

**Comment by rams23** [comment]
Hi @emilbonnek thanks for your contribution, why do you say that it makes the development harder? because of the need to rebuild de library? I do no agree to much on the direct import from src, but we can discuss about it
