### ISSUE TITLE
Import declaration conflicts with local declaration of 'Action'

### ISSUE THREAD

**Issue by emilbonnek** [xtreamsrl/firebase-ngrx-user-management#3]
After upgrading to angular version 9 and typescript 3.7 I get this error:
`Import declaration conflicts with local declaration of 'Action'`
from **lib/effects/custom-email-handler.effects.d.ts**.
It seems to be because of a [change to how typescript 3.7 handles duplicate type declarations](
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#local-and-imported-type-declarations-now-conflict).
I tried removing line 7
`export declare type Action = customEmailHandlerActions.CustomEmailHandlerActionsUnion;`
It does the trick in allowing the compiler to move on. Perhaps it causes problems with the email handling functionality I haven't been able to confirm or deny that.

**Comment by rooswelt** [comment]
Any news on this?

**Comment by BuligaRobert** [comment]
Any news on this or the update to Angular 9?
